export const USERNOTYETIDCONSTANT = "USER_NOT_YET_CONSTANT_ID";
export const USERAVAILABLEIDCONSTANT = "USER_AVAILABLE_CONSTANT_ID";
export const USERWAITINGTOACCEPTIDCONSTANT =
  "USER_WAITING_TO_ACCEPT_CONSTANT_ID";
export const USERCORFIMWITHID = "USER_CORFIM_WITH_ID";
export const USERCONFIRMWAITINGWITHID = "USER_CONFIRM_WAITING_WITH_ID";
export const USERCANCELWITHID = "USER_CANCEL_WITH_ID";
