export const USERNOTYETCONSTANT = "USER_NOT_YET_CONSTANT";
export const USERAVAILABLECONSTANT = "USER_AVAILABLE_CONSTANT";
export const USERWAITINGTOACCEPTCONSTANT = "USER_WAITING_TO_ACCEPT_CONSTANT";
export const USER_CONFIRM = "USER_CONFIRM";
export const USER_CONFIRM_WAITING = "USER_CONFIRM_WAITING";
export const USER_CANCEL = "USER_CANCEL";
